### ISSUE TITLE
Refactoring  /structure 

### ISSUE THREAD

**Issue by J0MS** [fabianhjr/awesome-radical-decentralization#3]
@fabianhjr @stripedpajamas 
Just a comment, [/organizations](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/organizations) and [/communities ](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/communities) could be the same?

Could [/decentralized-applications](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/projects/decentralized-applications) go inside [/infrastructure](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/projects/infrastructure)?

**Comment by fabianhjr** [comment]
Communities is intended to be local oriented while some orgs have a global scope (P2P Foundation for example)

**Comment by J0MS** [comment]
Ok, and the same about of [/decentralized-applications](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/projects/decentralized-applications) go inside [/infrastructure](https://github.com/fabianhjr/awesome-radical-decentralization/tree/master/projects/infrastructure), right ?
